spring.application.name=Haru_Coding_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/HaruCoding
spring.datasource.username=postgres
spring.datasource.password=root1212
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Google Client
spring.security.oauth2.client.registration.google.client-id=164346625909-021m0jbdcf60ja0t63907btjvqlnmu63.apps.googleusercontent.com

jwt.secret=haruCoding-secret-key-be-senior-2026-spring-boot
jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=604800000