spring.application.name=Haru_Coding_backend

spring.datasource.url=${Haru_Coding_backend_DATASOURCE_URL}
spring.datasource.username=${Haru_Coding_backend_DATASOURCE_USERNAME}
spring.datasource.password=&{Haru_Coding_backend_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Google Client
spring.security.oauth2.client.registration.google.client-id=${Haru_Coding_backend_CLIENT_ID}

jwt.secret=haruCoding-secret-key-be-senior-2026-spring-boot
jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=604800000